[versions]
agp = "8.9.1"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycle = "2.9.4"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
appcompat = "1.7.1"
kotlinxSerializationJson = "1.9.0"
navigation3 = "1.0.0"
protobufKotlin = "4.32.0"
#scarlet = "0.2.4"
retrofit = "3.0.0"
kotlin-serialization = "2.2.0"
protobufGradlePlugin = "0.9.6"
okhttp3 = "5.1.0"
coil3 = "3.3.0"
pagingCompose = "3.3.6"
room = "2.8.4"
kspPlugin = "2.2.0-2.0.2"
media3 = "1.9.1"
composeShimmer = "1.3.3"
koin = "4.1.1"
documentfileVersion = "1.1.0"
exifinterface = "1.3.6"

[libraries]

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
#compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfileVersion" }

protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobufKotlin" }
#protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobufKotlin" }
#coil image preview
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil3" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
# websocket scarlet
#scarlet = { group = "com.github.Tinder.Scarlet", name = "scarlet", version.ref = "scarlet" }
#websocket-okhttp = { group = "com.github.Tinder.Scarlet", name = "websocket-okhttp", version.ref = "scarlet" }
#message-adapter-protobuf = { group = "com.github.Tinder.Scarlet", name = "message-adapter-protobuf", version.ref = "scarlet" }
#stream-adapter-coroutines = { group = "com.github.Tinder.Scarlet", name = "stream-adapter-coroutines", version.ref = "scarlet" }

okhttp3-okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp3" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp3-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines" }

androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "composeShimmer" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup"}
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp-gradle-plugin = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin" }
androidx-room = { id = "androidx.room", version.ref = "room" }
